name = input("Enter your name: ")
number1 = int(input("Enter your first number: "))
number2 = int(input("Enter your second number: ")) 

print("Hello " + name + " your results are out: ")
print(str(number1 + number2))
print(str(number1 - number2))
print(str(number1 * number2))
print(str(number1 / number2))
print(str(number1 % number2))
print(str(number1 ** number2))
print(str(number1 // number2))
print(str(number1 > number2))
print(str(number1 < number2))
print(str(number1 == number2))
print(str(number1 != number2))
print(str(number1 >= number2))
print(str(number1 <= number2))
print(str(number1 and number2))
print(str(number1 or number2))
print(str(not number1))
print(str(not number2))
print(str(number1 is number2))
print(str(number1 is not number2))
print(str(number1 in [number2]))
print(str(number1 not in [number2]))
print(str(number1 & number2))
print(str(number1 | number2))
print(str(number1 ^ number2))
print(str(number1 << number2))
print(str(number1 >> number2))
print(str(number1 if number1 > number2 else number2))
print(str(number1 if number1 < number2 else number2))
print(str(number1 if number1 == number2 else number2))
print(str(number1 if number1 != number2 else number2))
print(str(number1 if number1 >= number2 else number2))
print(str(number1 if number1 <= number2 else number2))
print(str(number1 if number1 and number2 else number2))
print(str(number1 if number1 or number2 else number2))
print(str(number1 if not number1 else number2))
print(str(number1 if not number2 else number2))
print(str(number1 if number1 is number2 else number2))
print(str(number1 if number1 is not number2 else number2))
print(str(number1 if number1 in [number2] else number2))
print(str(number1 if number1 not in [number2] else number2))
print(str(number1 if number1 & number2 else number2))
print(str(number1 if number1 | number2 else number2))
print(str(number1 if number1 ^ number2 else number2))
print(str(number1 if number1 << number2 else number2))
print(str(number1 if number1 >> number2 else number2))